[package]
name = "wireguard-vanity-address"
version = "0.2.1-alpha.0"
authors = ["Brian Warner <warner@lothar.com>"]
description = "Find Wireguard VPN keypairs with a specific readable string"
license = "MIT"
readme = "README.md"
categories = ["cryptography"]
documentation = "https://docs.rs/wireguard-vanity-address"
homepage = "https://github.com/warner/wireguard-vanity-address"
repository = "https://github.com/warner/wireguard-vanity-address"
exclude = [
    "**/.gitignore",
    ".gitignore",
]

[dependencies]
rayon = "1.0"
base64 = "0.10"
rand = "0.6.0"
x25519-dalek = { version = "0.4.4", default-features = false, features = ["std", "u64_backend"] }
